-- [GUEST 계정 접속]
-- 1. 테이블 생성
--    테이블명 : GUEST
--    컬럼 : 번호 GNO(PK), 이름 GNAME(NOT NULL), 나이 GAGE(1~150)
--            , 성별 GGENDER(M 또는 F), 주민번호 GSID(UNIQUE), 접속일시 GCONNDT(NOT NULL)
CREATE TABLE GUEST (
	GNO NUMBER PRIMARY KEY,
	GNAME VARCHAR2(20) NOT NULL,
	GAGE NUMBER CHECK (GAGE BETWEEN 1 AND 150),
	GGENDER CHAR(1) CHECK (GGENDER IN ('M', 'F')),
	GSID VARCHAR2(14) UNIQUE,
	GCONNDT DATE NOT NULL
);

-- 2. 시퀀스 생성
--    시퀀스명 : SEQ_GUEST (1부터 1씩 증가 최대 1000, NOCYCLE, NOCACHE)
CREATE SEQUENCE SEQ_GUEST
INCREMENT BY 1
START WITH 1
MAXVALUE  1000
NOCYCLE
NOCACHE;


-- [GUEST 테이블]
-- 임의의 데이터 5건 입력
INSERT INTO GUEST VALUES(SEQ_GUEST.NEXTVAL, '홍길동', 20, 'M', '000000-0000000', SYSDATE);
INSERT INTO GUEST VALUES(SEQ_GUEST.NEXTVAL, '김길순', 30, 'F', '100000-0000000', SYSDATE);
INSERT INTO GUEST VALUES(SEQ_GUEST.NEXTVAL, '최길동', 40, 'M', '200000-0000000', SYSDATE);
INSERT INTO GUEST VALUES(SEQ_GUEST.NEXTVAL, '이길순', 50, 'F', '300000-0000000', SYSDATE);
INSERT INTO GUEST VALUES(SEQ_GUEST.NEXTVAL, '박길동', 60, 'M', '400000-0000000', SYSDATE);

SELECT * FROM GUEST;











