CREATE TABLE PRODUCT (
	PNO NUMBER PRIMARY KEY, -- 품번
	PCOMP VARCHAR2(200), -- 제조사
	PNAME VARCHAR2(200), -- 상품명
	PCOLOR VARCHAR2(200), -- 색상
	PAMT NUMBER, -- 수량
	PPRICE NUMBER, -- 가격
	PMDATE DATE -- 제조일시
);

CREATE SEQUENCE SEQ_PRODUCT;